# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
  - master
  - 2.0.0
skip_tags: true
os: unstable
platform:
- x64
cache: false
test: off
install:
# - ps: Install-Product node $env:nodejs_version $env:platform
- ps: Install-Product node 10 $env:platform
- SET CI=true
- npm install --global yarn
- set PATH=%PATH%;C:\.yarn\bin
- node --version
- npm --version
- yarn --version
- yarn install --pure-lockfile --mutex file
- yarn generate-npm-lockfile
- npm audit
build_script:
- yarn run app:dist
- yarn run electron-builder:publish:x64
