# TODO figure how to make YAML anchors work in appveyor config file, it doesn't recognize anchors

# TODO improve artifacts sharing between the jobs, keep track of the following issues:
# - https://github.com/appveyor/ci/issues/2438
# - https://github.com/appveyor/ci/issues/1623

# TODO try using "appveyor" for building all platforms packages and drop "travis-ci" use then
# https://www.appveyor.com/docs/linux-images-software/
# https://www.appveyor.com/docs/macos-images-software/
# https://www.appveyor.com/docs/windows-images-software/

branches:
  only:
    - master

skip_tags: true
platform:
  - x64
build: off
test: off
stack: node $nodejs_version

matrix:
  fast_finish: true

environment:
  nodejs_version: 12
  nodejs_arch: x64
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  LINUX_JOB_NAME: 'build proton clients (linux)'
  LINUX_JOB_ARTIFACT_TAR: 'webclients-artifact.tar'
  matrix:
    - job_name: 'build proton clients (linux)'
      appveyor_build_worker_image: 'Ubuntu1804'
    - job_name: 'build app (windows)'
      appveyor_build_worker_image: 'Visual Studio 2017'
      job_depends_on: 'build proton clients (linux)'
    - job_name: 'build app (macos-catalina)'
      appveyor_build_worker_image: 'macos'
      job_depends_on: 'build proton clients (linux)'
    - job_name: 'build app (macos-mojave)'
      appveyor_build_worker_image: 'macos-mojave'
      job_depends_on: 'build proton clients (linux)'

before_build:
  - node --version
  - npm --version
  - yarn --version
  - npx envinfo
  - yarn install --pure-lockfile
build_script:
  - yarn scripts/ci/appveyor/download-webclients-artifact
  - yarn app:dist
  # - yarn test:e2e
  - yarn electron-builder:dist
  - yarn scripts/dist-packages/print-hashes
  - yarn scripts/dist-packages/upload
on_failure:
  - ps: Get-Process
  - sh: tar -cvf e2e-logs.tar ./output/e2e
  - cmd: 7z a e2e-logs.tar output\e2e\
  - yarn scripts/transfer upload e2e-logs.tar

for:
  - matrix:
      only:
        - job_name: 'build app (windows)'
    install:
      - cmd: powershell Install-Product node $env:nodejs_version $env:nodejs_arch
      - ps: |
          (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
          cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
  - matrix:
      only:
        - job_name: 'build proton clients (linux)'
    cache:
      # - $HOME/.npm
      # - $HOME/.cache/yarn
      - ./output/git
    install:
      - nvm install $nodejs_version
      - ./scripts/ci/appveyor/install-linux.sh
    build_script: echo "overridden"
    after_build: ./scripts/ci/appveyor/build-linux.sh
    on_failure: echo "overridden"
  - matrix:
      only:
        - job_name: 'build app (macos-catalina)'
    environment:
      ARTIFACT_NAME_POSTFIX: '-catalina'
    install:
      # - HOMEBREW_NO_INSTALL_CLEANUP=1 brew cask install firefox
      - nvm install $nodejs_version
      - |
        curl -o- -L https://yarnpkg.com/install.sh | bash;
        export PATH="$HOME/.yarn/bin:$PATH";
  - matrix:
      only:
        - job_name: 'build app (macos-mojave)'
    environment:
      ARTIFACT_NAME_POSTFIX: '-mojave'
    install:
      # - HOMEBREW_NO_INSTALL_CLEANUP=1 brew cask install firefox
      - nvm install $nodejs_version
      - |
        curl -o- -L https://yarnpkg.com/install.sh | bash;
        export PATH="$HOME/.yarn/bin:$PATH";
