# TODO improve artifacts sharng between the jobs, keep track of the following issues:
# - https://github.com/appveyor/ci/issues/2438
# - https://github.com/appveyor/ci/issues/1623
branches:
  only:
  - master
skip_tags: true
image:
  # items order matters
  - 'Ubuntu1804'
  - 'Visual Studio 2017'
platform:
  - x64
build: off
test: off
matrix:
  fast_finish: true
stack: node $nodejs_version
environment:
  nodejs_version: 12
  nodejs_arch: x64
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  LINUX_JOB_NAME_PATTERN: 'image: Ubuntu1804'
  LINUX_JOB_ARTIFACT_TAR: 'webclients-artifact.tar'
install:
  - sh: ./scripts/ci/appveyor/install-linux.sh
  - cmd: powershell Install-Product node $env:nodejs_version $env:nodejs_arch
  - ps: |
      (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
      cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
  - node --version
  - npm --version
  - yarn --version
  - npx envinfo
  - yarn install --pure-lockfile
for:
  - matrix:
      only:
        - image: 'Ubuntu1804'
    cache:
      - ./output/git
    build_script: ./scripts/ci/appveyor/build-linux.sh
  - matrix:
      only:
        - image: 'Visual Studio 2017'
    build_script:
      - ps: | # download and extract prepared by linux job web clients
          $headers = @{
            "Authorization" = "Bearer $EMAIL_SECURELY_APP_APPVEYOR_API_KEY"
            "Content-type" = "application/json"
          }
          $project = Invoke-RestMethod -Uri "https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG" -Headers $headers -Method GET
          $linuxJob = $project.build.jobs | where { $_.name -eq $env:LINUX_JOB_NAME_PATTERN }
          $linuxJobId = $linuxJob.jobId;
          $linuxJobCompleted = $linuxJob.status -eq "success"
          if (!$linuxJobCompleted){
            throw "Job `"$env:LINUX_JOB_NAME_PATTERN`" has been finished with `"$linuxJob.status`" status"
          }
          if (!$linuxJobId) {
            throw "Failed to resolve i`"$env:LINUX_JOB_NAME_PATTERN`" job id"
          }
          Start-FileDownload https://ci.appveyor.com/api/buildjobs/$linuxJobId/artifacts/$env:LINUX_JOB_ARTIFACT_TAR
          7z x $env:LINUX_JOB_ARTIFACT_TAR
      - ps: | # actual build
          yarn app:dist
          yarn electron-builder:dist
          yarn scripts/dist-packages/print-hashes
          yarn scripts/dist-packages/upload
    on_failure:
      - ps: Get-Process
      - SET APP_E2E_ARTIFACT_LOG=appveyor-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_JOB_NUMBER%-e2e-logs.zip
      - 7z a %APP_E2E_ARTIFACT_LOG% .\output\e2e\*
      - dir
      - appveyor PushArtifact %APP_E2E_ARTIFACT_LOG%
