# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
skip_tags: true
os: unstable
#environment:
#  matrix:
#    - nodejs_version: 8
platform:
  - x64
cache:
  - "%LOCALAPPDATA%/Yarn"
  - "%USERPROFILE%/.electron"
  - "%USERPROFILE%/.electron-builder"
test: off
install:
  # - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: Install-Product node 8 $env:platform
  - SET CI=true
  - npm install --global yarn
  - set PATH=%PATH%;C:\.yarn\bin
  - node --version
  - npm --version
  - yarn --version
  - yarn install --mutex file
build_script:
  - yarn run app:dist
  - yarn run electron-builder:release:x64
